modLoader="javafml"
loaderVersion="[4,)"
license="Academic Free License v3.0"

[[mods]]
modId="minigames"
version="3"
displayName="Minigames"
displayURL="https://www.curseforge.com/minecraft/mc-mods/minigames"
credits="FL_F3rno"
authors="Gli FL"
description="A mod with a few innovative minigames"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "minigames.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.minigames]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.minigames]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration